workspace = { members = ["csrc"] }
[package]
name = "atoma-paged-attention"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle-core = "0.6.0"
candle-nn = "0.6.0"
candle-transformers = "0.6.0"
csrc = { path = "csrc" }
serde = { version = "1.0.204", features = ["derive"] }
tracing = "0.1.40"

[dev-dependencies]
candle-examples = "0.6.0"
hf-hub = "0.3.2"
serde_json = "1.0.120"
tokenizers = "0.19.1"
