[package]
name = "atoma-paged-attention"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle = { git = "https://github.com/huggingface/candle", package = "candle-core", branch = "main", features = ["cuda"] }
candle-nn = { git = "https://github.com/huggingface/candle", package = "candle-nn", branch = "main", features = ["cuda"] }
candle-transformers = { git = "https://github.com/huggingface/candle", package = "candle-transformers", branch = "main", features = ["cuda", "flash-attn"] }
half = "2.4.1"
serde = { version = "1.0.203", features = ["derive"] }
