[package]
name = "csrc"
version = "0.1.0"
edition = "2021"
description = "Paged attention kernels for Atoma"
categories = ["science"]
license = "MIT OR Apache-2.0"

[dependencies]

[build-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bindgen_cuda = "0.1.1"
